# Generated by Django 5.2.8 on 2026-01-29 20:51

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="نام کاربری"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="ادمین"),
                ),
                ("is_teacher", models.BooleanField(default=False, verbose_name="معلم")),
                ("is_staff", models.BooleanField(default=False, verbose_name="مدیر")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_student",
                    models.BooleanField(default=False, verbose_name="دانش اموز"),
                ),
                (
                    "is_parents",
                    models.BooleanField(default=False, verbose_name="والدین"),
                ),
                ("is_user", models.BooleanField(default=True, verbose_name="کاربر")),
                (
                    "created_date",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_date", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربر ها",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="NewUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تلفن"),
                ),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newusers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر جدید",
                "verbose_name_plural": "کاربرهای جدید",
            },
        ),
        migrations.CreateModel(
            name="Parents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="نام خانوادگی"),
                ),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "updated_date",
                    django_jalali.db.models.jDateField(
                        auto_now=True, verbose_name="زمان اپدیت"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "والدین",
                "verbose_name_plural": "والدین",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "name_st",
                    models.CharField(max_length=250, verbose_name="نام دانش اموز"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره موبایل"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("School facilities", "امکانات مدرسه"),
                            ("teaching method", "روش تدریس"),
                            ("behavior", "رفتار معلمان"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=250,
                        verbose_name="موضوع",
                    ),
                ),
                ("comment", models.TextField(verbose_name="نظر شما")),
                ("status", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("show", models.BooleanField(default=False, verbose_name="نمایش")),
                (
                    "created_date",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_Parents",
                        to="accounts.parents",
                        verbose_name="والدین",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProfileAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="کاربر", max_length=250, verbose_name="نام"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="نام خانوادگی"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles",
                        verbose_name="تصویر",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("role", models.CharField(max_length=250, verbose_name="نقش")),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("updated_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ادمین",
                "verbose_name_plural": "ادمین ها",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="نام خانوادگی"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("هفتم", "هفتم"),
                            ("هشتم", "هشتم"),
                            ("نهم", "نهم"),
                            ("دهم کامپیوتر", "دهم کامپیوتر"),
                            ("دهم حسابداری", "دهم حسابداری"),
                            ("یازدهم کامپیوتر", "یازدهم کامپیوتر"),
                            ("یازدهم حسابداری", "یازدهم حسابداری"),
                            ("دوازدهم کامپیوتر", "دوازدهم کامپیوتر"),
                            ("دوازدهم حسابداری", "دوازدهم حسابداری"),
                        ],
                        default="دهم کامپیوتر",
                        verbose_name="پایه\u200cی تحصیلی",
                    ),
                ),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "updated_date",
                    django_jalali.db.models.jDateField(
                        auto_now=True, verbose_name="زمان اپدیت"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانش آموز",
                "verbose_name_plural": "دانش آموزان",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="parents",
            name="child",
            field=models.ManyToManyField(
                related_name="parents", to="accounts.student", verbose_name="فرزند ها"
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم درس")),
                ("grade", models.CharField(max_length=200, verbose_name="پایه تحصیلی")),
                ("year", models.CharField(max_length=200, verbose_name="سال تحصیلی")),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="lessons",
                        to="accounts.student",
                        verbose_name="دانش اموزان",
                    ),
                ),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "درس ها",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("فروردین", "فروردین"),
                            ("اردیبهشت", "اردیبهشت"),
                            ("خرداد", "خرداد"),
                            ("مهر", "مهر"),
                            ("آبان", "آبان"),
                            ("آذر", "آذر"),
                            ("دی", "دی"),
                            ("بهمن", "بهمن"),
                            ("اسفند", "اسفند"),
                        ],
                        default="مهر",
                        verbose_name="ماه",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="نمره باید بین ۰ تا ۲۰ باشد",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="نمره",
                    ),
                ),
                (
                    "class_activity",
                    models.FloatField(
                        help_text="نمره فعالیت کلاسی باید بین ۰ تا ۲۰ باشد",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="فعالیت کلاسی",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("average", "متوسط"),
                            ("good", "خوب"),
                            ("great", "عالی"),
                        ],
                        default="good",
                        max_length=250,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                (
                    "updated_date",
                    django_jalali.db.models.jDateField(
                        auto_now=True, verbose_name="بروزرسانی"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="accounts.lesson",
                        verbose_name="درس",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="accounts.student",
                        verbose_name="دانش آموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمره",
                "verbose_name_plural": "نمره ها",
                "ordering": ("-month",),
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غایب"),
                            ("late", "تاخیر"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="ناریخ"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendancerecords",
                        to="accounts.lesson",
                        verbose_name="درس",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendancerecords",
                        to="accounts.student",
                        verbose_name="دانش آموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور و غیاب",
                "verbose_name_plural": "حضور و غیاب ها",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "full_name_en",
                    models.CharField(
                        max_length=250,
                        unique=True,
                        verbose_name="نام و نام خانوادگی به انگلیسی",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="teacher", verbose_name="عکس"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("degree", models.CharField(max_length=250, verbose_name="مدرک")),
                (
                    "teaching_experience",
                    models.IntegerField(default=0, verbose_name="سابقه دریس"),
                ),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "updated_date",
                    django_jalali.db.models.jDateField(
                        auto_now=True, verbose_name="زمان اپدیت"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلم",
                "verbose_name_plural": "معلم ها",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="accounts.teacher",
                verbose_name="معلم",
            ),
        ),
        migrations.CreateModel(
            name="TeacherContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=250, verbose_name="نام دانش اموز"),
                ),
                (
                    "subject",
                    models.CharField(max_length=250, verbose_name="موضوع پیام"),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachercontacts",
                        to="accounts.student",
                        verbose_name="دانش اموز",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachercontacts",
                        to="accounts.teacher",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام معلم",
                "verbose_name_plural": "پیام های معلم",
                "ordering": ("-id",),
            },
        ),
    ]
