# Generated by Django 5.2.8 on 2026-02-27 14:48

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="accounts.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "تکلیف",
                "verbose_name_plural": "تکالیف",
                "ordering": ("-id",),
            },
        ),
    ]
