# Generated by Django 5.2.8 on 2026-02-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="accounts.teacher",
            ),
            preserve_default=False,
        ),
    ]
