# Generated by Django 5.2.8 on 2026-02-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_assignment_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.BooleanField(default=False, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="accounts.lesson",
                verbose_name="درس",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="accounts.teacher",
                verbose_name="معلم",
            ),
        ),
    ]
