# Generated by Django 5.2.8 on 2026-01-29 20:51

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تلفن"),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                ("read", models.BooleanField(default=False, verbose_name="خوانده شده")),
                ("created_date", django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام ها",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="GalleryCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی گالری",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای گالری",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                ("image", models.ImageField(upload_to="gallerys", verbose_name="عکس")),
                ("status", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="images", to="home.gallerycategories"
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس",
                "verbose_name_plural": "عکس ها",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="محتوا")),
                ("image", models.ImageField(upload_to="news", verbose_name="عکس")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("read", models.IntegerField(default=0, verbose_name="زمان خواندن")),
                ("views", models.IntegerField(default=0, verbose_name="بازدید")),
                ("status", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("special", models.BooleanField(default=False, verbose_name="ویژه")),
                (
                    "created_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="اپدیت"
                    ),
                ),
                (
                    "updated_date",
                    django_jalali.db.models.jDateField(
                        auto_now=True, verbose_name="اپدیت"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "خبر\u200cها\u200c",
                "ordering": ("-id",),
            },
        ),
    ]
